version: '3.8'


services:
  tex_cirq_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/workspace/src
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]



